### ISSUE TITLE
RC Receiver without starting ppm signal

### ISSUE THREAD

**Issue by cver019** [dimag0g/PPM-reader#1]
Hi,

My issue is that for some reason my receiver does not appear to have a starting pulse.
It is an older model When i add multiple channels together than then program works fine, however it is n-1. So I rough work around would be to add a throw away channel. Or rework the code such that it counts the pulses and uses a "CHANGE" ISR versus a rising edge rigger only.
Hoping I can upload oscilloscope pictures to show the issue later on today

**Comment by cver019** [comment]
![IMG_0428V2](https://user-images.githubusercontent.com/101657215/158582195-49d76525-2bbe-4e82-9857-a46a831bd038.jpg)
![1](https://user-images.githubusercontent.com/101657215/158582475-0ad82d34-c798-435f-9a0a-1b4b113c5ed9.JPG)
![2](https://user-images.githubusercontent.com/101657215/158582479-c6da2415-f3b6-4df3-a874-57dc2746016d.JPG)
![3](https://user-images.githubusercontent.com/101657215/158582481-15f98611-54c3-49e8-b406-108cc904fc01.JPG)

The layout it top down on the RC receiver = left to right on the oscilloscope so Elev = blue, Aile = yellow, Throttl = Purple, Rudd, Green.
img 1 is a zoomed out image of only the Elev - other oscilloscope probes are disconnected
img 2 is a close up image of only the Elev - other oscilloscope probes are disconnected
img 3 is all 4 probes on their respective channels. 

They all line up - Purple/Throttl is the only one not in the 'neutral' position, it was all the way down so that's why that looks a bit odd.

Hope this shows my issue

**Comment by dimag0g** [comment]
@cver019 Could you post a link to the manual of your receiver, I can't find it online that easily?

As I understand your oscilloscope captures, there's only one channel per electrical signal. This is in contrast with RC PPM, where a single signal carries data from several channels. What I still don't understand is how the channel value is encoded: is it the pulse width that changes, pulse frequency, or pulse position, and if it's pulse position, then what is the reference (t=0)?

You also say you "add multiple channels together" - how is that done, and could you post the oscilloscope plot of the resulting signal? If pulses are merged together through an equivalent of a logical OR gate, then how do you determine which pulse is channel 1?

I still think I should avoid using interrupts on either edge. The current library drops the timing for the fist pulse (which is the blanking time, which carries no information). I could expose this value as "channel 0", and if that works for you, I'll be happy to implement the change, but I'd still like to see the receiver's manual, or your multi-channel osci capture, to properly document the change.

**Comment by cver019** [comment]
@dimag0g the channel is encoded via the pulse width. Looking at just the throttle signal, from memory the minimum pulse width is around 1.2mS = 0% throttle and the maximum is around 1.8mS =100% throttle. In terms of adding multiple channels together you could simply just wire them all into one electrical connection and the pulses would stagger since that's just an electrical OR of the digital pulses. The pulses are just already split out.
I will see if I can get a snapshot of 4 channels on one wire, as well as a snapshot of one frame with the throttle varying from positions 0% to 50% to 100%.

I think the reference point is the long dead band, similar to what your code is already doing.
Lastly, I won't have Oscilloscope access after tomorrow until Mid April so hoping I can get those images taken and uploaded shortly.

**Comment by cver019** [comment]
@dimag0g 
I was a bit off. As a minimum the channel width is 1.10mS, centered stick at 1.47mS, and maximum at 1.90mS pulse width. See images below - looking at the third pulse (Throttle). The last capture shows you a full data frame period. Again this is with 4 channels combined (hard wired) together. The pulse channels are top down on the RX and left to right on the O-Scope . e.g. Blue (Elev) is top = first pulse, green (Aile) is second = second pulse, etc

As can be seen, if the pulse width increases or decreases all pulses to the right of the width varying pulse is shifted accordingly. 
However the low/zero voltage time period between pulses are fixed.

Sorry about the pictures, the oscilloscope cannot take screen shots so I have to do it with my phone.
Any questions let me know

Thanks

![0 perc Throttle](https://user-images.githubusercontent.com/101657215/159392953-8c01bc2c-2db3-433a-96ce-f22dd3470805.JPG)
![50 perc Throttle](https://user-images.githubusercontent.com/101657215/159392954-c26d1cfc-1fa0-4a25-97d5-d637a426efc8.JPG)
![100 perc Throttle](https://user-images.githubusercontent.com/101657215/159392955-6fad81c5-2787-43b6-94af-655ab9233651.JPG)
![Data Frame](https://user-images.githubusercontent.com/101657215/159392957-a42daf5e-abcc-44c7-b315-c9aa0dcdc194.JPG)
d

**Comment by dimag0g** [comment]
@cver019 Thanks for the last oscilloscope pictures. I can now clearly see you have some sort of multi-channel PWM signal. The PPM reader is able to decode some of it, because if the gaps between individual pulses are constant, a PWM signal is just an inverted PPM signal with one pulse missing.

The terminology in RC community is a big mess indeed, which makes it hard to find the right libraries. E.g. [this](https://playground.arduino.cc/Code/ReadReceiver/) seems to be an example of a code which could receive multi-channel PWM, though the author calls it PPM. But the fact that both signal edges are measured is a good hint that pulse width is used, rather than pulse position. Here's [another](https://github.com/xkam1x/Arduino-PWM-Reader) library which does indeed measure pulse widths, but with "channels" actually being separate electrical signals. You could use it nevertheless, if you have enough pins. There may be other code samples or libraries which may work fine for cases like yours.

Unfortunately, I disagree with the idea that a PPM library should measure pulse widths (this is what would happen if an interrupt is fired on both edges). It would make no difference with ideal signals, but in case of distortions or non-standard signals doing so would make the PPM signal reception less precise:

- If rising and falling edges are asymmetrical, or the interrupt trigger level is not exactly in the middle between 0 and Umax, using both edges for timing will introduce errors which would not be there if only rising edges are used.
-  Another problem would be with radios which fail to produce PPM pulses of a constant width: the current PPM reader would not have a problem to decode such signals, but considering both edges may make the PPM reader fail to decode such non-standard signals properly.

For these reasons, I regret to tell you I'm not going to implement the proposed changes at this time. If you can live with the workaround where you add a dummy channel to satisfy the number of pulses required, you're welcome to use PPM reader. Otherwise I suggest you look for a different library, perhaps starting with the ones I have found.

**Comment by cver019** [comment]
Thanks for your response.
That makes a lot of sense.
I thought it was PWM (since its doing width modulation) but for some reason ruled that out early on, and figured it must be PPM as this my first time working with RC receivers and their signals.
Thanks for the suggested libraries and the info, I think I have a much better understanding of PPPM and PWM.

Again, I appreciate the feedback - Hopefully this will help someone else understand the difference between PPM and PWM 🙂

________________________________
